# Schema for the configuration files of the Spyglasses module.

spyglasses.settings:
  type: config_object
  label: 'Spyglasses settings'
  mapping:
    api_key:
      type: string
      label: 'API key'
    debug_mode:
      type: boolean
      label: 'Debug mode'
    auto_sync:
      type: boolean
      label: 'Auto-sync patterns'
    collector_endpoint:
      type: uri
      label: 'Collector endpoint'
    patterns_endpoint:
      type: uri
      label: 'Patterns endpoint'
    cache_ttl:
      type: integer
      label: 'Cache TTL'
    last_pattern_sync:
      type: integer
      label: 'Last pattern sync timestamp'
